---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  pre_tasks:
    - name: Instalando pacotes de dependencias para o curso
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - vim
        - unzip
        - python3
        - python3-pip
        - software-properties-common
        - python3-pymysql
        - python-pymysql
        update_cache: yes

    - name: Criando o arquivo get-pip.py
      copy:
        src: files/get-pip.py
        dest: /tmp
        mode: 0644

    - name: Atualiza o pip com Python 3
      shell: python3 get-pip.py
      args:
        chdir: /tmp

    - name: Instala zabbix-api via Pip
      pip:
        name: zabbix-api

  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 192.168.99.10 zabbix zabbix.dexter.com.br
        - 192.168.99.11 prometheus prometheus.dexter.com.br
        - 192.168.99.12 4flix 4flix.dexter.com.br
        - 192.168.99.13 graylog graylog.dexter.com.br

    - name: Adicionar usuario suporte
      user:
        name: suporte
        shell: /bin/bash
        password : $1$QbUARykG$p2nthVG8AkDvabKPHwboa1

    - name: Criando o arquivo 98_4linux
      copy:
        src: files/98_4linux
        dest: /etc/sudoers.d
        mode: 0644

    - name: Ajustando .bashrc do usuario vagrant
      lineinfile:
        path: /home/vagrant/.bashrc
        line: 'sudo su - suporte'

  roles:
    - role: roles/geerlingguy.apache
    - role: roles/geerlingguy.php
      php_default_version_debian: "7.2"
      php_fpm_state: started
      php_fpm_enabled_on_boot: true
      php_fpm_handler_state: restarted
      php_fpm_listen: "127.0.0.1:9000"
      php_fpm_listen_allowed_clients: "127.0.0.1"
      php_fpm_pm_max_children: 50
      php_fpm_pm_start_servers: 5
      php_fpm_pm_min_spare_servers: 5
      php_fpm_pm_max_spare_servers: 5
      php_use_managed_ini: true

    - role: roles/geerlingguy.mysql
      mysql_root_password: '4linux-root!@#'
      mysql_databases:
        - name: zabbix
          encoding: utf8
          collation: utf8_bin
      mysql_users:
        - name: zabbix
          host: "localhost"
          password: 4linux
          priv: "zabbix.*:ALL"

    - role: roles/ansible_collections/community/zabbix/roles/zabbix_server
      zabbix_server_version: 4.4
      zabbix_repo: zabbix
      zabbix_server_database: mysql
      zabbix_server_database_long: mysql
      zabbix_server_dbhost: localhost
      zabbix_server_dbport: 3306
      zabbix_server_dbname: zabbix
      zabbix_server_dbuser: zabbix
      zabbix_server_dbpassword: 4linux

    - role: roles/ansible_collections/community/zabbix/roles/zabbix_web
      zabbix_web_version: 4.4
      zabbix_url: zabbix.dexter.com.br
      zabbix_timezone: America/Sao_Paulo
      zabbix_web_max_execution_time: 300
      zabbix_web_memory_limit: 128
      zabbix_web_post_max_size: 16
      zabbix_web_upload_max_filesize: 2
      zabbix_web_max_input_time: 300
      zabbix_php_version: 7.2
      zabbix_php_fpm_dir: /etc/php/7.2/fpm/pool.d
